Repository kalviumcommunity/S64_Jayant_Capstone_NexusHub, pull requests merged in 2025-06, with the labels that each got.

#20 Update and Delete
  backend/controllers/postController.js
  backend/routes/postRoutes.js
  backend/uploads/media-1751105341938-239098610.jpeg
  backend/uploads/media-1751105341938-839672516.jpeg
  backend/uploads/media-1751105341945-978215226.jpg
  client/src/components/feed/PostCard.jsx
  client/src/components/feed/RightSidebar.jsx
  client/src/context/FeedContext.jsx
  client/src/utils/api.js
Labels: Review effort 3/5, Possible security concern

#21 Fix: Make sidebar responsive for mobile and desktop views
  client/package-lock.json
  client/src/App.jsx
  client/src/components/dock/Dock.css
  client/src/components/dock/Dock.jsx
  client/src/components/dock/DockDemo.jsx
  client/src/pages/CreatePost.jsx
  client/src/pages/Feed.jsx
Labels: Review effort 4/5

#22 Explore page
  client/src/App.jsx
  client/src/components/ui/SidebarLayout.jsx
  client/src/components/ui/sidebar.jsx
  client/src/pages/Explore.jsx
Labels: Review effort 3/5
